import { ScrollView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { MaterialIcons } from "@expo/vector-icons";
import { ScreenContainer } from "@/components/screen-container";
import { Card, IconButton, palette, PrimaryButton, SectionTitle } from "@/components/trennix-ui";
import { weeklyPlan } from "@/lib/trennix/data";

export default function ScheduleScreen() {
  return <ScreenContainer className="px-5 pt-3"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}><View style={styles.header}><IconButton name="arrow-back" onPress={() => router.back()} /><View><Text style={styles.kicker}>SEMANA 22</Text><Text style={styles.title}>Agenda de treinos</Text></View><IconButton name="calendar-today" /></View><View style={styles.days}>{weeklyPlan.map((item, index) => <View key={item.date} style={[styles.day, index === 0 && styles.dayActive]}><Text style={[styles.dayName, index === 0 && styles.dayActiveText]}>{item.day}</Text><Text style={[styles.dayDate, index === 0 && styles.dayActiveText]}>{item.date}</Text>{item.done ? <MaterialIcons name="check-circle" size={14} color={palette.bg} /> : <View style={styles.dot} />}</View>)}</View><SectionTitle eyebrow="segunda-feira · 26 de maio" title="Peito e Tríceps" /><Card style={styles.workoutCard}><View style={styles.workoutIcon}><MaterialIcons name="fitness-center" size={25} color={palette.lime}/></View><View style={styles.workoutCopy}><Text style={styles.workoutTitle}>Força · Bloco A</Text><Text style={styles.workoutMeta}>6 exercícios · 55 min</Text></View><View style={styles.done}><MaterialIcons name="check" size={18} color={palette.bg}/></View></Card><View style={styles.upcoming}><SectionTitle title="Próximos dias" />{weeklyPlan.slice(1).map((item) => <Card key={item.date} style={styles.row}><View style={styles.dateBox}><Text style={styles.dateNumber}>{item.date}</Text><Text style={styles.dateDay}>{item.day}</Text></View><View style={styles.rowCopy}><Text style={styles.rowTitle}>{item.title}</Text><Text style={styles.rowMeta}>{item.done ? "Concluído" : "Planejado"}</Text></View><MaterialIcons name="chevron-right" color={palette.muted} size={21}/></Card>)}</View><PrimaryButton label="Iniciar treino de hoje" icon="play-arrow" onPress={() => router.push("/workout")} /></ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { paddingBottom: 30 }, header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 26 }, kicker: { color: palette.lime, fontSize: 10, letterSpacing: 1.3, fontWeight: "900" }, title: { color: palette.text, fontSize: 22, fontWeight: "900", marginTop: 4 }, days: { flexDirection: "row", justifyContent: "space-between", marginBottom: 30 }, day: { width: 55, height: 76, borderRadius: 17, backgroundColor: palette.surface, borderWidth: 1, borderColor: palette.border, alignItems: "center", justifyContent: "center", gap: 3 }, dayActive: { backgroundColor: palette.lime, borderColor: palette.lime }, dayName: { color: palette.muted, fontSize: 10, fontWeight: "900" }, dayDate: { color: palette.text, fontSize: 18, fontWeight: "900" }, dayActiveText: { color: palette.bg }, dot: { width: 5, height: 5, borderRadius: 3, backgroundColor: palette.border }, workoutCard: { flexDirection: "row", alignItems: "center", padding: 14 }, workoutIcon: { width: 50, height: 50, borderRadius: 15, backgroundColor: "#243522", alignItems: "center", justifyContent: "center", marginRight: 13 }, workoutCopy: { flex: 1 }, workoutTitle: { color: palette.text, fontSize: 16, fontWeight: "800" }, workoutMeta: { color: palette.muted, fontSize: 12, marginTop: 4 }, done: { width: 30, height: 30, backgroundColor: palette.lime, borderRadius: 15, alignItems: "center", justifyContent: "center" }, upcoming: { marginTop: 28 }, row: { flexDirection: "row", alignItems: "center", padding: 13, marginBottom: 8 }, dateBox: { width: 43, alignItems: "center" }, dateNumber: { color: palette.text, fontWeight: "900", fontSize: 17 }, dateDay: { color: palette.muted, fontSize: 9, fontWeight: "800" }, rowCopy: { flex: 1, marginLeft: 12 }, rowTitle: { color: palette.text, fontWeight: "700", fontSize: 14 }, rowMeta: { color: palette.muted, marginTop: 3, fontSize: 11 }, });
