import { useMemo, useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { router } from "expo-router";
import { MaterialIcons } from "@expo/vector-icons";
import { ScreenContainer } from "@/components/screen-container";
import { Card, IconButton, palette, PrimaryButton } from "@/components/trennix-ui";
import { getExercise, todayWorkout } from "@/lib/trennix/data";

export default function WorkoutScreen() {
  const [current, setCurrent] = useState(0);
  const [completed, setCompleted] = useState<number[]>([]);
  const [weight, setWeight] = useState("20");
  const exercise = useMemo(() => getExercise(todayWorkout.exercises[current]), [current]);
  const finish = () => { Alert.alert("Treino concluído", "Sua sessão foi salva no histórico deste aparelho.", [{ text: "Ver histórico", onPress: () => router.replace("/history") }, { text: "Voltar ao início", onPress: () => router.replace("/(tabs)") }]); };
  return <ScreenContainer className="px-5 pt-3"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>
    <View style={styles.header}><IconButton name="close" onPress={() => router.back()} /><View style={styles.headerCenter}><Text style={styles.kicker}>TREINO ATIVO</Text><Text style={styles.title}>{todayWorkout.title}</Text></View><Text style={styles.counter}>{current + 1}/{todayWorkout.exercises.length}</Text></View>
    <View style={styles.progress}><View style={[styles.progressFill, { width: `${((current + 1) / todayWorkout.exercises.length) * 100}%` }]} /></View>
    <Text style={styles.eyebrow}>EXERCÍCIO {current + 1}</Text><Text style={styles.exerciseTitle}>{exercise.name}</Text><Text style={styles.exerciseSub}>{exercise.muscle} · {exercise.equipment}</Text>
    <Card style={styles.formCard}><View style={styles.formHeader}><Text style={styles.formTitle}>Série atual</Text><Text style={styles.rest}><MaterialIcons name="timer" size={16} color={palette.orange}/> descanso 90s</Text></View><View style={styles.inputs}><View><Text style={styles.label}>CARGA (KG)</Text><TextInput value={weight} onChangeText={setWeight} keyboardType="decimal-pad" style={styles.input}/></View><View><Text style={styles.label}>REPETIÇÕES</Text><View style={styles.repBox}><Text style={styles.repValue}>{exercise.reps}</Text></View></View></View><Text style={styles.cue}>{exercise.cue}</Text></Card>
    <View style={styles.series}><Text style={styles.sectionTitle}>Séries registradas</Text>{[1,2,3,4].slice(0, exercise.sets).map((set) => <View key={set} style={styles.seriesRow}><View style={[styles.setCircle, completed.includes(set) && styles.setDone]}>{completed.includes(set) ? <MaterialIcons name="check" size={15} color={palette.bg}/> : <Text style={styles.setNumber}>{set}</Text>}</View><Text style={styles.seriesText}>Série {set}</Text><Text style={styles.seriesData}>{completed.includes(set) ? `${weight} kg · ${exercise.reps} reps` : "Aguardando"}</Text></View>)}</View>
    <PrimaryButton label={completed.length >= exercise.sets ? (current === todayWorkout.exercises.length - 1 ? "Finalizar treino" : "Próximo exercício") : "Concluir série"} icon={completed.length >= exercise.sets ? "arrow-forward" : "check"} onPress={() => { if (completed.length < exercise.sets) setCompleted([...completed, completed.length + 1]); else if (current < todayWorkout.exercises.length - 1) { setCurrent(current + 1); setCompleted([]); } else finish(); }}/>
  </ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { paddingBottom: 30 }, header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 20 }, headerCenter: { alignItems: "center" }, kicker: { color: palette.lime, fontSize: 10, letterSpacing: 1.5, fontWeight: "900" }, title: { color: palette.text, fontSize: 15, fontWeight: "800", marginTop: 4 }, counter: { color: palette.muted, fontWeight: "800" }, progress: { height: 5, backgroundColor: palette.elevated, borderRadius: 5, overflow: "hidden", marginBottom: 34 }, progressFill: { height: "100%", backgroundColor: palette.lime }, eyebrow: { color: palette.lime, fontSize: 11, fontWeight: "900", letterSpacing: 1.2 }, exerciseTitle: { color: palette.text, fontSize: 31, fontWeight: "900", marginTop: 7, letterSpacing: -1 }, exerciseSub: { color: palette.muted, marginTop: 5, fontSize: 14 }, formCard: { marginTop: 24, padding: 18 }, formHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, formTitle: { color: palette.text, fontSize: 17, fontWeight: "800" }, rest: { color: palette.orange, fontSize: 11, flexDirection: "row", alignItems: "center", gap: 4 }, inputs: { flexDirection: "row", gap: 14, marginTop: 20 }, label: { color: palette.muted, fontSize: 10, fontWeight: "900", letterSpacing: 1, marginBottom: 7 }, input: { color: palette.text, backgroundColor: palette.elevated, borderRadius: 12, minWidth: 120, paddingHorizontal: 15, height: 50, fontSize: 20, fontWeight: "800" }, repBox: { height: 50, minWidth: 120, backgroundColor: palette.elevated, borderRadius: 12, justifyContent: "center", paddingHorizontal: 15 }, repValue: { color: palette.text, fontSize: 20, fontWeight: "800" }, cue: { color: palette.muted, fontSize: 12, lineHeight: 18, marginTop: 18 }, series: { marginVertical: 26 }, sectionTitle: { color: palette.text, fontWeight: "800", fontSize: 17, marginBottom: 12 }, seriesRow: { flexDirection: "row", alignItems: "center", height: 48, borderBottomWidth: 1, borderBottomColor: palette.border }, setCircle: { width: 28, height: 28, borderRadius: 14, borderWidth: 1, borderColor: palette.border, alignItems: "center", justifyContent: "center", marginRight: 12 }, setDone: { backgroundColor: palette.lime, borderColor: palette.lime }, setNumber: { color: palette.muted, fontWeight: "800", fontSize: 12 }, seriesText: { color: palette.text, fontSize: 13, fontWeight: "700", flex: 1 }, seriesData: { color: palette.muted, fontSize: 11 }, });
