import { Platform } from "react-native";
import * as SecureStore from "expo-secure-store";
import type { AIProvider } from "./store";
const KEY="trennix.ai-key.v1";
export async function readAiKey(){try{return Platform.OS==="web"?window.sessionStorage.getItem(KEY):await SecureStore.getItemAsync(KEY)}catch{return null}}
export async function saveAiKey(value:string){const key=value.trim();if(Platform.OS==="web"){if(key)window.sessionStorage.setItem(KEY,key);else window.sessionStorage.removeItem(KEY);return}if(key)await SecureStore.setItemAsync(KEY,key);else await SecureStore.deleteItemAsync(KEY)}
async function compatible(base:string,key:string,model:string,question:string,context:string){const res=await fetch(`${base}/chat/completions`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${key}`},body:JSON.stringify({model,temperature:.35,messages:[{role:"system",content:`Você é o treinador inteligente do TRENNIX. Responda em português do Brasil com objetividade e segurança. Não substitua orientação profissional. Contexto: ${context}`},{role:"user",content:question}]})});if(!res.ok)throw new Error("A IA não respondeu. Confira a chave e o modelo.");const data=await res.json();return data?.choices?.[0]?.message?.content??"Não consegui gerar uma resposta agora."}
async function gemini(key:string,model:string,question:string,context:string){const res=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${encodeURIComponent(key)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({contents:[{parts:[{text:`Você é o treinador inteligente do TRENNIX. Responda em português. Contexto: ${context}\nPergunta: ${question}`}]}]})});if(!res.ok)throw new Error("O Gemini não respondeu. Confira a chave e o modelo.");const data=await res.json();return data?.candidates?.[0]?.content?.parts?.[0]?.text??"Não consegui gerar uma resposta agora."}
async function claude(key:string,model:string,question:string,context:string){const res=await fetch("https://api.anthropic.com/v1/messages",{method:"POST",headers:{"Content-Type":"application/json","x-api-key":key,"anthropic-version":"2023-06-01","anthropic-dangerous-direct-browser-access":"true"},body:JSON.stringify({model,max_tokens:700,system:`Você é o treinador inteligente do TRENNIX. Responda em português. Contexto: ${context}`,messages:[{role:"user",content:question}]})});if(!res.ok)throw new Error("O Claude não respondeu. Confira a chave e o modelo.");const data=await res.json();return data?.content?.[0]?.text??"Não consegui gerar uma resposta agora."}
async function manus(key:string,model:string,question:string,context:string){const created=await fetch("https://api.manus.ai/v2/task.create",{method:"POST",headers:{"Content-Type":"application/json","x-manus-api-key":key},body:JSON.stringify({title:"TRENNIX IA Coach",locale:"pt-BR",interactive_mode:false,hide_in_task_list:true,agent_profile:model,message:{role:"user",content:`Você é o treinador do TRENNIX. Responda em português. Contexto: ${context}\nPergunta: ${question}`}})});if(!created.ok)throw new Error("O Manus IA não aceitou a chave.");const task=await created.json();if(!task?.task_id)throw new Error("O Manus IA não retornou uma tarefa.");for(let i=0;i<20;i++){await new Promise(r=>setTimeout(r,1500));const res=await fetch(`https://api.manus.ai/v2/task.listMessages?task_id=${encodeURIComponent(task.task_id)}&order=desc&limit=50`,{headers:{"x-manus-api-key":key}});const data=await res.json();const text=(data?.data??[]).flatMap((x:any)=>x?.content??[]).map((x:any)=>typeof x==="string"?x:x?.text).find((x:any)=>typeof x==="string"&&x.length>12);if(text)return text}throw new Error("O Manus IA demorou mais que o esperado.")}
export async function askTrennixAI(question:string,context:string,provider:AIProvider="groq",model="llama-3.3-70b-versatile"){const key=await readAiKey();if(!key)throw new Error("Cole sua chave da IA em Configurações para conversar com o treinador.");if(provider==="gemini")return gemini(key,model,question,context);if(provider==="claude")return claude(key,model,question,context);if(provider==="manus")return manus(key,model,question,context);const base=provider==="chatgpt"?"https://api.openai.com/v1":provider==="deepseek"?"https://api.deepseek.com":"https://api.groq.com/openai/v1";return compatible(base,key,model,question,context)}
