export type MuscleGroup="Peito"|"Pernas"|"Costas"|"Braços";
export type Exercise={id:string;name:string;muscle:MuscleGroup;equipment:string;sets:number;reps:string;level:"Base"|"Intermediário"|"Avançado";cue:string};
export type Workout={id:string;title:string;subtitle:string;duration:string;exerciseCount:number;accent:string;exercises:string[];kind:"Casa"|"Academia"};
export const exercises:Exercise[]=[
{id:"push-up",name:"Flexão de braços",muscle:"Peito",equipment:"Peso corporal",sets:4,reps:"10–15",level:"Base",cue:"Mantenha o corpo alinhado e desça com controle."},{id:"diamond-push-up",name:"Flexão diamante",muscle:"Peito",equipment:"Peso corporal",sets:3,reps:"8–12",level:"Intermediário",cue:"Aproxime as mãos sob o peito sem perder o alinhamento."},{id:"bench",name:"Supino reto",muscle:"Peito",equipment:"Barra",sets:4,reps:"8–10",level:"Base",cue:"Mantenha os ombros apoiados e desça a barra com controle."},{id:"incline",name:"Supino inclinado",muscle:"Peito",equipment:"Halteres",sets:3,reps:"10–12",level:"Base",cue:"Empurre os halteres em linha com o peito alto."},{id:"fly",name:"Crucifixo",muscle:"Peito",equipment:"Halteres",sets:3,reps:"10–12",level:"Base",cue:"Abra os braços com leve flexão nos cotovelos."},{id:"squat",name:"Agachamento livre",muscle:"Pernas",equipment:"Peso corporal",sets:4,reps:"12–15",level:"Base",cue:"Desça mantendo o joelho acompanhando a ponta do pé."},{id:"lunge",name:"Afundo alternado",muscle:"Pernas",equipment:"Peso corporal",sets:3,reps:"10 cada",level:"Base",cue:"Dê um passo firme e mantenha o tronco alto."},{id:"legpress",name:"Leg press 45°",muscle:"Pernas",equipment:"Máquina",sets:3,reps:"10–12",level:"Base",cue:"Não trave os joelhos no topo da repetição."},{id:"rdl",name:"Levantamento terra romeno",muscle:"Pernas",equipment:"Halteres",sets:4,reps:"8–10",level:"Intermediário",cue:"Leve o quadril para trás mantendo a coluna neutra."},{id:"calf",name:"Elevação de panturrilha",muscle:"Pernas",equipment:"Peso corporal",sets:4,reps:"15–20",level:"Base",cue:"Faça uma pausa no alto do movimento."},{id:"row",name:"Remada curvada",muscle:"Costas",equipment:"Halteres",sets:4,reps:"8–10",level:"Intermediário",cue:"Trave o abdômen e puxe os cotovelos para trás."},{id:"lat-pulldown",name:"Puxada na frente",muscle:"Costas",equipment:"Cabo",sets:3,reps:"10–12",level:"Base",cue:"Inicie o movimento aproximando as escápulas."},{id:"superman",name:"Superman",muscle:"Costas",equipment:"Peso corporal",sets:3,reps:"12–15",level:"Base",cue:"Eleve braços e pernas sem forçar a lombar."},{id:"reverse-fly",name:"Crucifixo inverso",muscle:"Costas",equipment:"Halteres",sets:3,reps:"12–15",level:"Base",cue:"Abra os braços usando a parte posterior dos ombros."},{id:"curl",name:"Rosca direta",muscle:"Braços",equipment:"Halteres",sets:3,reps:"10–12",level:"Base",cue:"Mantenha os cotovelos próximos ao tronco."},{id:"hammer",name:"Rosca martelo",muscle:"Braços",equipment:"Halteres",sets:3,reps:"10–12",level:"Base",cue:"Mantenha as palmas voltadas uma para a outra."},{id:"triceps",name:"Tríceps na polia",muscle:"Braços",equipment:"Cabo",sets:3,reps:"10–12",level:"Base",cue:"Finalize a extensão sem afastar os cotovelos."},{id:"bench-dip",name:"Tríceps no banco",muscle:"Braços",equipment:"Banco",sets:3,reps:"10–15",level:"Base",cue:"Desça apenas até manter os ombros confortáveis."}
];
const make=(id:string,title:string,subtitle:string,duration:string,exercises:string[],kind:"Casa"|"Academia"):Workout=>({id,title,subtitle,duration,exercises,kind,exerciseCount:exercises.length,accent:kind==="Casa"?"#A8F238":"#65D66F"});
export const workouts:Workout[]=[
make("home-full","Corpo inteiro em casa","Base e consistência","28 min",["push-up","squat","superman","bench-dip"],"Casa"),make("home-upper","Superior sem equipamentos","Peito, costas e braços","24 min",["push-up","superman","diamond-push-up","bench-dip"],"Casa"),make("home-legs","Pernas e potência","Força usando o peso corporal","26 min",["squat","lunge","calf","superman"],"Casa"),make("home-chest","Peito em casa","Empurrar e controlar","22 min",["push-up","diamond-push-up","bench-dip"],"Casa"),make("home-back","Costas e postura","Estabilidade e controle","20 min",["superman","reverse-fly","lunge"],"Casa"),make("home-arms","Braços sem máquinas","Volume e resistência","23 min",["diamond-push-up","bench-dip","hammer"],"Casa"),
make("gym-push","Push na academia","Peito, ombros e tríceps","48 min",["bench","incline","fly","triceps"],"Academia"),make("gym-pull","Pull na academia","Costas e bíceps","50 min",["lat-pulldown","row","reverse-fly","curl"],"Academia"),make("gym-legs","Pernas completas","Força e volume","55 min",["squat","legpress","rdl","calf"],"Academia"),make("gym-chest","Peito e tríceps","Construção de força","45 min",["bench","incline","fly","triceps"],"Academia"),make("gym-back","Costas e bíceps","Puxada e espessura","48 min",["lat-pulldown","row","reverse-fly","hammer"],"Academia"),make("gym-full","Full body academia","Treino completo","60 min",["squat","bench","lat-pulldown","curl"],"Academia")
];
export function getExercise(id:string){return exercises.find(item=>item.id===id)??exercises[0]};
export const todayWorkout:Workout={id:"empty",title:"Nenhum treino criado",subtitle:"Monte pela Biblioteca",duration:"—",exerciseCount:0,accent:"#A8F238",exercises:[],kind:"Casa"};
export const weeklyPlan:{day:string;date:string;title:string;done:boolean}[]=[];
