export type MuscleGroup="Peito"|"Pernas"|"Costas"|"Braços"|"Ombros"|"Abdômen"|"Cardio / Corpo inteiro";
export type Environment="Casa"|"Academia";
export type Exercise={id:string;name:string;muscle:MuscleGroup;subunit?:string;equipment:string;sets:number;reps:string;level:"Base"|"Intermediário"|"Avançado";cue:string};
export type Workout={id:string;title:string;subtitle:string;duration:string;exerciseCount:number;accent:string;exercises:string[];kind:Environment;group:MuscleGroup};
const e=(id:string,name:string,muscle:MuscleGroup,equipment:string,subunit?:string):Exercise=>({id,name,muscle,subunit,equipment,sets:3,reps:"8–12",level:"Base",cue:"Execute com controle, amplitude confortável e postura estável."});
const legacy:Exercise[]=[
e("push-up","Flexão de braços","Peito","Peso corporal"),e("incline-push-up","Flexão inclinada","Peito","Apoio firme"),e("decline-push-up","Flexão declinada","Peito","Banco ou sofá"),e("diamond-push-up","Flexão diamante","Peito","Peso corporal"),e("bench","Supino reto","Peito","Barra"),e("incline","Supino inclinado","Peito","Halteres"),e("decline","Supino declinado","Peito","Barra"),e("fly","Crucifixo","Peito","Halteres"),e("floor-fly","Crucifixo no chão","Peito","Halteres"),e("squat","Agachamento livre","Pernas","Peso corporal"),e("lunge","Afundo alternado","Pernas","Peso corporal"),e("glute-bridge","Elevação pélvica","Pernas","Peso corporal"),e("legpress","Leg press 45°","Pernas","Máquina"),e("rdl","Levantamento terra romeno","Pernas","Halteres"),e("leg-extension","Cadeira extensora","Pernas","Máquina"),e("calf","Elevação de panturrilha","Pernas","Peso corporal"),e("row","Remada curvada","Costas","Halteres"),e("lat-pulldown","Puxada na frente","Costas","Cabo"),e("seated-row","Remada baixa","Costas","Cabo"),e("backpack-row","Remada com mochila","Costas","Mochila"),e("superman","Superman","Costas","Peso corporal"),e("bird-dog","Bird dog","Costas","Peso corporal"),e("reverse-fly","Crucifixo inverso","Costas","Halteres"),e("curl","Rosca direta","Braços","Barra"),e("hammer","Rosca martelo","Braços","Halteres"),e("triceps","Tríceps na polia","Braços","Cabo"),e("skullcrusher","Tríceps testa","Braços","Barra W"),e("chair-dip","Tríceps no banco","Braços","Banco"),e("backpack-curl","Rosca com mochila","Braços","Mochila")
];
legacy[4].sets=4;legacy[4].reps="8–10";
const academy:Exercise[]=[
// Pernas · Quadríceps
e("gym-squat","Agachamento livre","Pernas","Barra","Quadríceps"),e("gym-smith-squat","Agachamento no Smith","Pernas","Smith","Quadríceps"),e("gym-hack-squat","Agachamento no Hack","Pernas","Hack","Quadríceps"),e("gym-legpress45","Leg Press 45°","Pernas","Máquina","Quadríceps"),e("gym-legpress-horizontal","Leg Press horizontal","Pernas","Máquina","Quadríceps"),e("gym-extension","Cadeira extensora","Pernas","Máquina","Quadríceps"),e("gym-front-squat","Agachamento frontal","Pernas","Barra","Quadríceps"),e("gym-lunge","Afundo","Pernas","Halteres","Quadríceps"),e("gym-walking-lunge","Passada","Pernas","Halteres","Quadríceps"),e("gym-bulgarian","Bulgarian Split Squat","Pernas","Halteres","Quadríceps"),e("gym-step-up","Step-up","Pernas","Caixa","Quadríceps"),
// Pernas · Posterior de coxa
e("gym-leg-curl-lying","Mesa flexora","Pernas","Máquina","Posterior de coxa"),e("gym-leg-curl-seated","Cadeira flexora","Pernas","Máquina","Posterior de coxa"),e("gym-stiff","Stiff","Pernas","Barra","Posterior de coxa"),e("gym-rdl","Levantamento terra romeno","Pernas","Halteres","Posterior de coxa"),e("gym-good-morning","Good Morning","Pernas","Barra","Posterior de coxa"),e("gym-nordic","Flexão nórdica","Pernas","Peso corporal","Posterior de coxa"),
// Pernas · Glúteos
e("gym-hip-thrust","Hip Thrust","Pernas","Barra","Glúteos"),e("gym-pelvic","Elevação pélvica","Pernas","Barra","Glúteos"),e("gym-cable-kickback","Coice no cabo","Pernas","Cabo","Glúteos"),e("gym-glute-machine","Glúteo na máquina","Pernas","Máquina","Glúteos"),e("gym-abduction","Abdução de quadril","Pernas","Máquina","Glúteos"),e("gym-sumo","Agachamento sumô","Pernas","Halteres","Glúteos"),e("gym-bulgarian-glute","Afundo búlgaro","Pernas","Halteres","Glúteos"),
// Pernas · Panturrilha
e("gym-calf-standing","Panturrilha em pé","Pernas","Máquina","Panturrilha"),e("gym-calf-seated","Panturrilha sentado","Pernas","Máquina","Panturrilha"),e("gym-calf-legpress","Panturrilha no Leg Press","Pernas","Leg Press","Panturrilha"),e("gym-calf-smith","Panturrilha no Smith","Pernas","Smith","Panturrilha"),
// Peito · Peitoral
e("gym-bench-bar","Supino reto com barra","Peito","Barra","Peitoral"),e("gym-bench-dumbbell","Supino reto com halteres","Peito","Halteres","Peitoral"),e("gym-incline-bar","Supino inclinado com barra","Peito","Barra","Peitoral"),e("gym-incline-dumbbell","Supino inclinado com halteres","Peito","Halteres","Peitoral"),e("gym-decline-bench","Supino declinado","Peito","Barra","Peitoral"),e("gym-chest-press","Chest Press","Peito","Máquina","Peitoral"),e("gym-fly-dumbbell","Crucifixo com halteres","Peito","Halteres","Peitoral"),e("gym-incline-fly","Crucifixo inclinado","Peito","Halteres","Peitoral"),e("gym-machine-fly","Crucifixo na máquina","Peito","Máquina","Peitoral"),e("gym-crossover","Crossover","Peito","Cabo","Peitoral"),e("gym-crossover-high","Crossover alto","Peito","Cabo","Peitoral"),e("gym-crossover-low","Crossover baixo","Peito","Cabo","Peitoral"),e("gym-pushup","Flexão de braço","Peito","Peso corporal","Peitoral"),e("gym-chest-dips","Paralelas para peito","Peito","Barras paralelas","Peitoral"),
// Costas · Dorsais
e("gym-pullup","Barra fixa","Costas","Barra fixa","Dorsais"),e("gym-front-pulldown","Puxada frontal","Costas","Cabo","Dorsais"),e("gym-supinated-pulldown","Puxada supinada","Costas","Cabo","Dorsais"),e("gym-neutral-pulldown","Puxada neutra","Costas","Cabo","Dorsais"),e("gym-single-pulldown","Puxada unilateral","Costas","Cabo","Dorsais"),e("gym-barbell-row","Remada curvada","Costas","Barra","Dorsais"),e("gym-one-arm-row","Remada unilateral com halter","Costas","Halter","Dorsais"),e("gym-tbar-row","Remada cavalinho","Costas","Barra T","Dorsais"),e("gym-low-row","Remada baixa","Costas","Cabo","Dorsais"),e("gym-machine-row","Remada articulada","Costas","Máquina","Dorsais"),e("gym-seated-machine-row","Remada na máquina","Costas","Máquina","Dorsais"),e("gym-pulldown","Pulldown","Costas","Máquina","Dorsais"),e("gym-cable-pullover","Pullover no cabo","Costas","Cabo","Dorsais"),e("gym-dumbbell-pullover","Pullover com halter","Costas","Halter","Dorsais"),
// Costas · Lombar
e("gym-back-extension","Extensão lombar","Costas","Banco romano","Lombar"),e("gym-hyperextension","Hiperextensão","Costas","Banco romano","Lombar"),e("gym-deadlift","Levantamento terra","Costas","Barra","Lombar"),e("gym-lower-good-morning","Good Morning","Costas","Barra","Lombar"),
// Braços · Bíceps
e("gym-barbell-curl","Rosca direta com barra","Braços","Barra","Bíceps"),e("gym-dumbbell-curl","Rosca direta com halteres","Braços","Halteres","Bíceps"),e("gym-alternating-curl","Rosca alternada","Braços","Halteres","Bíceps"),e("gym-hammer-curl","Rosca martelo","Braços","Halteres","Bíceps"),e("gym-scott-curl","Rosca Scott","Braços","Banco Scott","Bíceps"),e("gym-concentration-curl","Rosca concentrada","Braços","Halter","Bíceps"),e("gym-incline-curl","Rosca inclinada","Braços","Halteres","Bíceps"),e("gym-cable-curl","Rosca no cabo","Braços","Cabo","Bíceps"),e("gym-21-curl","Rosca 21","Braços","Barra","Bíceps"),e("gym-spider-curl","Rosca spider","Braços","Banco","Bíceps"),
// Braços · Tríceps
e("gym-pushdown","Tríceps na polia","Braços","Cabo","Tríceps"),e("gym-rope-pushdown","Tríceps corda","Braços","Corda","Tríceps"),e("gym-straight-bar-pushdown","Tríceps barra reta","Braços","Barra reta","Tríceps"),e("gym-french-press","Tríceps francês","Braços","Halter","Tríceps"),e("gym-skullcrusher","Tríceps testa","Braços","Barra W","Tríceps"),e("gym-kickback","Tríceps coice","Braços","Halter","Tríceps"),e("gym-single-pushdown","Tríceps unilateral no cabo","Braços","Cabo","Tríceps"),e("gym-close-bench","Supino fechado","Braços","Barra","Tríceps"),e("gym-dips","Paralelas","Braços","Barras paralelas","Tríceps"),e("gym-overhead-extension","Extensão de tríceps acima da cabeça","Braços","Cabo","Tríceps"),
// Braços · Antebraço
e("gym-wrist-curl","Rosca de punho","Braços","Barra","Antebraço"),e("gym-reverse-wrist-curl","Rosca de punho inversa","Braços","Barra","Antebraço"),e("gym-finger-flexion","Flexão de dedos","Braços","Peso corporal","Antebraço"),e("gym-wrist-extension","Extensão de punho","Braços","Halter","Antebraço"),
// Ombros · Deltoide anterior
e("gym-shoulder-press-bar","Desenvolvimento com barra","Ombros","Barra","Deltoide anterior"),e("gym-shoulder-press-dumbbell","Desenvolvimento com halteres","Ombros","Halteres","Deltoide anterior"),e("gym-shoulder-press-smith","Desenvolvimento no Smith","Ombros","Smith","Deltoide anterior"),e("gym-shoulder-press-machine","Desenvolvimento na máquina","Ombros","Máquina","Deltoide anterior"),e("gym-arnold-press","Arnold Press","Ombros","Halteres","Deltoide anterior")
];
const home:Exercise[]=[
// Casa · Peito
e("home-flexao","Flexão de braço","Peito","Peso corporal","Peitoral"),e("home-flexao-aberta","Flexão aberta","Peito","Peso corporal","Peitoral"),e("home-flexao-fechada","Flexão fechada","Peito","Peso corporal","Peitoral"),e("home-flexao-diamante","Flexão diamante","Peito","Peso corporal","Peitoral"),e("home-flexao-inclinada","Flexão inclinada","Peito","Apoio firme","Peitoral"),e("home-flexao-declinada","Flexão declinada","Peito","Banco ou sofá","Peitoral"),e("home-flexao-joelhos","Flexão com joelhos apoiados","Peito","Peso corporal","Peitoral"),e("home-flexao-arqueiro","Flexão arqueiro","Peito","Peso corporal","Peitoral"),e("home-flexao-explosiva","Flexão explosiva","Peito","Peso corporal","Peitoral"),e("home-flexao-unilateral","Flexão unilateral assistida","Peito","Apoio","Peitoral"),e("home-flexao-pausa","Flexão com pausa","Peito","Peso corporal","Peitoral"),e("home-pseudo-planche","Flexão pseudo planche","Peito","Peso corporal","Peitoral"),
// Casa · Costas
e("home-superman","Superman","Costas","Peso corporal","Dorsais"),e("home-superman-alt","Superman alternado","Costas","Peso corporal","Dorsais"),e("home-bird-dog","Bird Dog","Costas","Peso corporal","Dorsais"),e("home-remada-mochila","Remada com mochila","Costas","Mochila","Dorsais"),e("home-remada-unilateral","Remada unilateral com mochila","Costas","Mochila","Dorsais"),e("home-remada-elastico","Remada com elástico","Costas","Elástico","Dorsais"),e("home-pullover-mochila","Pullover com mochila","Costas","Mochila","Dorsais"),e("home-remada-invertida","Remada invertida","Costas","Mesa ou barra","Dorsais"),e("home-barra-fixa","Barra fixa","Costas","Barra fixa","Dorsais"),e("home-barra-supinada","Barra fixa supinada","Costas","Barra fixa","Dorsais"),e("home-barra-neutra","Barra fixa neutra","Costas","Barra fixa","Dorsais"),e("home-isometria-barra","Isometria na barra","Costas","Barra fixa","Dorsais"),
// Casa · Braços · Bíceps
e("home-rosca-mochila","Rosca com mochila","Braços","Mochila","Bíceps"),e("home-rosca-unilateral","Rosca unilateral com mochila","Braços","Mochila","Bíceps"),e("home-rosca-elastico","Rosca com elástico","Braços","Elástico","Bíceps"),e("home-rosca-isometrica","Rosca isométrica","Braços","Mochila","Bíceps"),e("home-chin-up","Chin-up","Braços","Barra fixa","Bíceps"),e("home-chin-up-apoio","Chin-up com apoio","Braços","Barra fixa","Bíceps"),
// Casa · Braços · Tríceps
e("home-triceps-banco","Tríceps banco/cadeira","Braços","Banco ou cadeira","Tríceps"),e("home-triceps-diamante","Flexão diamante","Braços","Peso corporal","Tríceps"),e("home-triceps-mochila","Tríceps acima da cabeça com mochila","Braços","Mochila","Tríceps"),e("home-triceps-elastico","Tríceps com elástico","Braços","Elástico","Tríceps"),e("home-triceps-unilateral","Tríceps unilateral","Braços","Peso corporal","Tríceps"),
// Casa · Braços · Antebraço
e("home-flexao-punho","Flexão de punho","Braços","Peso corporal","Antebraço"),e("home-extensao-punho","Extensão de punho","Braços","Peso corporal","Antebraço"),e("home-aperto-toalha","Aperto de toalha","Braços","Toalha","Antebraço"),e("home-pegada","Isometria de pegada","Braços","Toalha","Antebraço"),
// Casa · Ombros · Deltoides
e("home-pike","Pike Push-Up","Ombros","Peso corporal","Deltoides"),e("home-pike-elevado","Pike Push-Up com pés elevados","Ombros","Banco","Deltoides"),e("home-lateral-garrafas","Elevação lateral com garrafas","Ombros","Garrafas","Deltoides"),e("home-frontal-garrafas","Elevação frontal com garrafas","Ombros","Garrafas","Deltoides"),e("home-desenvolvimento-mochila","Desenvolvimento com mochila","Ombros","Mochila","Deltoides"),e("home-desenvolvimento-elastico","Desenvolvimento com elástico","Ombros","Elástico","Deltoides"),e("home-crucifixo-garrafas","Crucifixo inverso com garrafas","Ombros","Garrafas","Deltoides"),e("home-face-pull","Face Pull com elástico","Ombros","Elástico","Deltoides"),e("home-handstand-hold","Handstand Hold","Ombros","Peso corporal","Deltoides"),e("home-handstand-pushup","Handstand Push-Up","Ombros","Peso corporal","Deltoides"),
// Casa · Pernas · Quadríceps
e("home-agachamento","Agachamento livre","Pernas","Peso corporal","Quadríceps"),e("home-agachamento-sumo","Agachamento sumô","Pernas","Peso corporal","Quadríceps"),e("home-agachamento-pausa","Agachamento com pausa","Pernas","Peso corporal","Quadríceps"),e("home-agachamento-salto","Agachamento com salto","Pernas","Peso corporal","Quadríceps"),e("home-agachamento-bulgaro","Agachamento búlgaro","Pernas","Peso corporal","Quadríceps"),e("home-unilateral-assistido","Agachamento unilateral assistido","Pernas","Apoio","Quadríceps"),e("home-afundo","Afundo","Pernas","Peso corporal","Quadríceps"),e("home-passada","Passada","Pernas","Peso corporal","Quadríceps"),e("home-passada-reversa","Passada reversa","Pernas","Peso corporal","Quadríceps"),e("home-step-up","Step-up","Pernas","Escada ou banco","Quadríceps"),e("home-wall-sit","Wall Sit","Pernas","Parede","Quadríceps"),e("home-sissy","Sissy Squat","Pernas","Peso corporal","Quadríceps"),
// Casa · Pernas · Posterior de coxa
e("home-stiff-mochila","Stiff com mochila","Pernas","Mochila","Posterior de coxa"),e("home-stiff-unilateral","Stiff unilateral","Pernas","Peso corporal","Posterior de coxa"),e("home-ponte-posterior","Ponte de posterior","Pernas","Peso corporal","Posterior de coxa"),e("home-nordica","Flexão nórdica","Pernas","Peso corporal","Posterior de coxa"),e("home-toalha","Flexão de joelhos com toalha","Pernas","Toalha","Posterior de coxa"),e("home-good-morning","Good Morning com mochila","Pernas","Mochila","Posterior de coxa"),
// Casa · Pernas · Glúteos
e("home-elevacao-pelvica","Elevação pélvica","Pernas","Peso corporal","Glúteos"),e("home-hip-thrust","Hip Thrust","Pernas","Sofá ou banco","Glúteos"),e("home-ponte-gluteos","Ponte de glúteos","Pernas","Peso corporal","Glúteos"),e("home-ponte-unilateral","Ponte unilateral","Pernas","Peso corporal","Glúteos"),e("home-coice","Coice","Pernas","Peso corporal","Glúteos"),e("home-abducao","Abdução de quadril","Pernas","Elástico","Glúteos"),e("home-fire-hydrant","Fire Hydrant","Pernas","Peso corporal","Glúteos"),e("home-sumo-gluteo","Agachamento sumô","Pernas","Peso corporal","Glúteos"),e("home-afundo-gluteo","Afundo búlgaro","Pernas","Peso corporal","Glúteos"),
// Casa · Pernas · Panturrilha
e("home-panturrilha","Panturrilha em pé","Pernas","Peso corporal","Panturrilha"),e("home-panturrilha-unilateral","Panturrilha unilateral","Pernas","Peso corporal","Panturrilha"),e("home-panturrilha-degrau","Panturrilha no degrau","Pernas","Degrau","Panturrilha"),e("home-panturrilha-sentado","Panturrilha sentado","Pernas","Peso corporal","Panturrilha"),e("home-panturrilha-mochila","Panturrilha com mochila","Pernas","Mochila","Panturrilha"),
// Casa · Abdômen
e("home-abdominal","Abdominal tradicional","Abdômen","Peso corporal","Abdômen"),e("home-abdominal-supra","Abdominal supra","Abdômen","Peso corporal","Abdômen"),e("home-abdominal-infra","Abdominal infra","Abdômen","Peso corporal","Abdômen"),e("home-bicicleta","Abdominal bicicleta","Abdômen","Peso corporal","Abdômen"),e("home-elevar-pernas","Elevação de pernas","Abdômen","Peso corporal","Abdômen"),e("home-elevar-joelhos","Elevação de joelhos","Abdômen","Peso corporal","Abdômen"),e("home-canivete","Abdominal canivete","Abdômen","Peso corporal","Abdômen"),e("home-reverso","Abdominal reverso","Abdômen","Peso corporal","Abdômen"),e("home-russian-twist","Russian Twist","Abdômen","Peso corporal","Abdômen"),e("home-mountain-climber","Mountain Climber","Abdômen","Peso corporal","Abdômen"),e("home-prancha","Prancha","Abdômen","Peso corporal","Abdômen"),e("home-prancha-lateral","Prancha lateral","Abdômen","Peso corporal","Abdômen"),e("home-prancha-ombro","Prancha com toque no ombro","Abdômen","Peso corporal","Abdômen"),e("home-dead-bug","Dead Bug","Abdômen","Peso corporal","Abdômen"),e("home-hollow","Hollow Body Hold","Abdômen","Peso corporal","Abdômen"),e("home-v-up","V-Up","Abdômen","Peso corporal","Abdômen"),e("home-flutter","Flutter Kicks","Abdômen","Peso corporal","Abdômen"),e("home-heel-touch","Heel Touch","Abdômen","Peso corporal","Abdômen"),e("home-obliquo","Abdominal oblíquo","Abdômen","Peso corporal","Abdômen"),
// Casa · Cardio / Corpo inteiro
e("home-polichinelo","Polichinelo","Cardio / Corpo inteiro","Peso corporal","Cardio / Corpo inteiro"),e("home-polichinelo-lateral","Polichinelo lateral","Cardio / Corpo inteiro","Peso corporal","Cardio / Corpo inteiro"),e("home-corrida-estacionaria","Corrida estacionária","Cardio / Corpo inteiro","Peso corporal","Cardio / Corpo inteiro"),e("home-joelhos-altos","Corrida com joelhos altos","Cardio / Corpo inteiro","Peso corporal","Cardio / Corpo inteiro"),e("home-butt-kicks","Butt Kicks","Cardio / Corpo inteiro","Peso corporal","Cardio / Corpo inteiro"),e("home-burpee","Burpee","Cardio / Corpo inteiro","Peso corporal","Cardio / Corpo inteiro"),e("home-burpee-salto","Burpee com salto","Cardio / Corpo inteiro","Peso corporal","Cardio / Corpo inteiro"),e("home-skater","Skater","Cardio / Corpo inteiro","Peso corporal","Cardio / Corpo inteiro"),e("home-afundo-salto","Afundo com salto","Cardio / Corpo inteiro","Peso corporal","Cardio / Corpo inteiro"),e("home-corda","Corda","Cardio / Corpo inteiro","Corda","Cardio / Corpo inteiro"),e("home-shadow-boxing","Shadow Boxing","Cardio / Corpo inteiro","Peso corporal","Cardio / Corpo inteiro"),e("home-bear-crawl","Bear Crawl","Cardio / Corpo inteiro","Peso corporal","Cardio / Corpo inteiro"),e("home-crab-walk","Crab Walk","Cardio / Corpo inteiro","Peso corporal","Cardio / Corpo inteiro"),e("home-inchworm","Inchworm","Cardio / Corpo inteiro","Peso corporal","Cardio / Corpo inteiro")
];
export const exercises:Exercise[]=[...legacy,...academy,...home];
export const homeUnits:{name:MuscleGroup;subunits:string[];caption:string}[]=[{name:"Peito",subunits:["Peitoral"],caption:"Flexões e variações de peito"},{name:"Costas",subunits:["Dorsais"],caption:"Costas, puxadas e postura"},{name:"Braços",subunits:["Bíceps","Tríceps","Antebraço"],caption:"Braços e força de pegada"},{name:"Ombros",subunits:["Deltoides"],caption:"Desenvolvimento e estabilidade"},{name:"Pernas",subunits:["Quadríceps","Posterior de coxa","Glúteos","Panturrilha"],caption:"Pernas, glúteos e panturrilhas"},{name:"Abdômen",subunits:["Abdômen"],caption:"Core e estabilidade"},{name:"Cardio / Corpo inteiro",subunits:["Cardio / Corpo inteiro"],caption:"Condicionamento e movimentos completos"}];
export const academyUnits:{name:MuscleGroup;subunits:string[];caption:string}[]=[{name:"Pernas",subunits:["Quadríceps","Posterior de coxa","Glúteos","Panturrilha"],caption:"Coxas, glúteos e panturrilhas"},{name:"Peito",subunits:["Peitoral"],caption:"Peitoral e movimentos de empurrar"},{name:"Costas",subunits:["Dorsais","Lombar"],caption:"Dorsais, espessura e lombar"},{name:"Braços",subunits:["Bíceps","Tríceps","Antebraço"],caption:"Bíceps, tríceps e antebraço"},{name:"Ombros",subunits:["Deltoide anterior"],caption:"Desenvolvimento e força"}];
const make=(id:string,title:string,subtitle:string,duration:string,kind:Environment,group:MuscleGroup,ids:string[]):Workout=>({id,title,subtitle,duration,kind,group,exercises:ids,exerciseCount:ids.length,accent:kind==="Casa"?"#A8F238":"#65D66F"});
export const workouts:Workout[]=[
make("home-chest-strength","Peito em força","Peito, ombros e tríceps","25 min","Casa","Peito",["push-up","decline-push-up","chair-dip"]),make("home-chest-volume","Peito em volume","Controle e resistência","22 min","Casa","Peito",["push-up","incline-push-up","floor-fly"]),make("home-chest-beginner","Peito iniciante","Base para começar","18 min","Casa","Peito",["incline-push-up","push-up","chair-dip"]),make("home-back-strength","Costas em força","Postura e estabilidade","25 min","Casa","Costas",["backpack-row","superman","bird-dog"]),make("home-back-volume","Costas em volume","Puxada e controle","23 min","Casa","Costas",["backpack-row","superman","bird-dog"]),make("home-back-beginner","Costas iniciante","Movimento e postura","18 min","Casa","Costas",["bird-dog","superman","backpack-row"]),make("home-arms-strength","Braços em força","Bíceps e tríceps","24 min","Casa","Braços",["backpack-curl","chair-dip","diamond-push-up"]),make("home-arms-volume","Braços em volume","Resistência local","22 min","Casa","Braços",["backpack-curl","chair-dip","push-up"]),make("home-arms-beginner","Braços iniciante","Controle e técnica","18 min","Casa","Braços",["backpack-curl","chair-dip","incline-push-up"]),make("home-legs-strength","Pernas em força","Coxas e glúteos","28 min","Casa","Pernas",["squat","lunge","glute-bridge","calf"]),make("home-legs-volume","Pernas em volume","Resistência e potência","25 min","Casa","Pernas",["squat","glute-bridge","lunge"]),make("home-legs-beginner","Pernas iniciante","Base e equilíbrio","20 min","Casa","Pernas",["squat","glute-bridge","calf"])
];
export function getExercise(id:string){return exercises.find(item=>item.id===id)??exercises[0]};
export const todayWorkout:Workout={id:"empty",title:"Nenhum treino criado",subtitle:"Monte pela Biblioteca",duration:"—",exerciseCount:0,accent:"#A8F238",exercises:[],kind:"Casa",group:"Peito"};
export const weeklyPlan:{day:string;date:string;title:string;done:boolean}[]=[];
