import * as SecureStore from "expo-secure-store";
import { Platform } from "react-native";
import { createContext, PropsWithChildren, useContext, useEffect, useMemo, useState } from "react";
import type { Exercise } from "./data";
import { clearLocalData, readLocalData, writeLocalData } from "./persistence";
export type Profile={name:string;age:string;height:string;weight:string;photo:string|null};
export type AIProvider="chatgpt"|"groq"|"manus"|"gemini"|"claude"|"deepseek";export type Preferences={units:"kg / cm"|"lb / in";reminders:boolean;language:"Português"|"English";reminderHour:number;reminderMinute:number;aiProvider:AIProvider;aiModel:string};
export type ScheduledWorkout={day:number;title:string;exerciseIds:string[]};
export type Session={id:string;date:string;title:string;exerciseIds:string[];volume:number};
const defaultProfile:Profile={name:"",age:"",height:"",weight:"",photo:null};
const defaultPreferences:Preferences={units:"kg / cm",reminders:false,language:"Português",reminderHour:18,reminderMinute:0,aiProvider:"groq",aiModel:"llama-3.3-70b-versatile"};
const defaultSchedule:ScheduledWorkout[]=[]; const defaultSessions:Session[]=[]; const AI_KEY="trennix.ai-key.v1";
async function readAi(){try{return Platform.OS==="web"?window.sessionStorage.getItem(AI_KEY):await SecureStore.getItemAsync(AI_KEY)}catch{return null}}
async function writeAi(value:string){if(Platform.OS==="web")window.sessionStorage.setItem(AI_KEY,value);else await SecureStore.setItemAsync(AI_KEY,value)}
async function removeAi(){if(Platform.OS==="web")window.sessionStorage.removeItem(AI_KEY);else await SecureStore.deleteItemAsync(AI_KEY)}
function StoreProviderInner({children}:PropsWithChildren){const [profile,setProfile]=useState(defaultProfile);const [preferences,setPreferences]=useState(defaultPreferences);const [schedule,setSchedule]=useState(defaultSchedule);const [sessions,setSessions]=useState(defaultSessions);const [aiKeySaved,setAiKeySaved]=useState(false);const [hydrated,setHydrated]=useState(false);useEffect(()=>{readLocalData().then(data=>{if(data.profile)setProfile(data.profile as Profile);if(data.preferences)setPreferences({...defaultPreferences,...data.preferences as Partial<Preferences>});if(data.schedule)setSchedule(data.schedule as ScheduledWorkout[]);if(data.sessions)setSessions(data.sessions as Session[]);return readAi()}).then(key=>{setAiKeySaved(Boolean(key));setHydrated(true)});},[]);const persist=(next:{profile?:Profile;preferences?:Preferences;schedule?:ScheduledWorkout[];sessions?:Session[]})=>writeLocalData({profile:next.profile??profile,preferences:next.preferences??preferences,schedule:next.schedule??schedule,sessions:next.sessions??sessions});const updateProfile=async(next:Partial<Profile>)=>{const value={...profile,...next};setProfile(value);await persist({profile:value})};const updatePreferences=async(next:Partial<Preferences>)=>{const value={...preferences,...next};setPreferences(value);await persist({preferences:value})};const addToSchedule=async(day:number,title:string,exerciseIds:string[])=>{const existing=schedule.find(x=>x.day===day);const value=[...schedule.filter(x=>x.day!==day),{day,title:existing?.title??title,exerciseIds:Array.from(new Set([...(existing?.exerciseIds??[]),...exerciseIds]))}].sort((a,b)=>a.day-b.day);setSchedule(value);await persist({schedule:value})};const removeSchedule=async(day:number)=>{const value=schedule.filter(x=>x.day!==day);setSchedule(value);await persist({schedule:value})};const completeSession=async(title:string,exerciseIds:string[],volume:number)=>{const value=[{id:Date.now().toString(),date:new Date().toISOString(),title,exerciseIds,volume},...sessions];setSessions(value);await persist({sessions:value})};const saveAiKey=async(value:string)=>{if(value.trim()){await writeAi(value.trim());setAiKeySaved(true)}else{await removeAi();setAiKeySaved(false)}};const clearAll=async()=>{await clearLocalData();await removeAi();setProfile(defaultProfile);setPreferences(defaultPreferences);setSchedule([]);setSessions([]);setAiKeySaved(false)};const store=useMemo(()=>({profile,preferences,schedule,sessions,aiKeySaved,hydrated,updateProfile,updatePreferences,addToSchedule,removeSchedule,completeSession,saveAiKey,clearAll}),[profile,preferences,schedule,sessions,aiKeySaved,hydrated]);return <StoreContext.Provider value={store}>{children}</StoreContext.Provider>}
const StoreContext=createContext<ReturnType<typeof useStoreValue>|null>(null);function useStoreValue(){return {profile:defaultProfile,preferences:defaultPreferences,schedule:defaultSchedule,sessions:defaultSessions,aiKeySaved:false,hydrated:false,updateProfile:async(_:Partial<Profile>)=>{},updatePreferences:async(_:Partial<Preferences>)=>{},addToSchedule:async(_:number,__:string,___:string[])=>{},removeSchedule:async(_:number)=>{},completeSession:async(_:string,__:string[],___:number)=>{},saveAiKey:async(_:string)=>{},clearAll:async()=>{}}}
export function TrennixProvider({children}:PropsWithChildren){return <StoreProviderInner>{children}</StoreProviderInner>};export function useTrennixStore(){const value=useContext(StoreContext);if(!value)throw new Error("TrennixStore ausente");return value};export function dayLabel(day:number){return ["Domingo","Segunda","Terça","Quarta","Quinta","Sexta","Sábado"][day]};export function exercisesForSchedule(schedule:ScheduledWorkout[],catalog:Exercise[]){return schedule.map(item=>({...item,exercises:item.exerciseIds.map(id=>catalog.find(x=>x.id===id)?.name).filter(Boolean)}))}
