import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { MaterialIcons } from "@expo/vector-icons";
import { ScreenContainer } from "@/components/screen-container";
import { Card, IconButton, palette, PrimaryButton, SectionTitle } from "@/components/trennix-ui";
import { exercises } from "@/lib/trennix/data";
import { dayLabel, useTrennixStore } from "@/lib/trennix/store";
export default function AgendaScreen(){const {schedule,removeSchedule}=useTrennixStore();const now=new Date();const today=now.getDay();const [selectedDay,setSelectedDay]=useState(today);const monday=new Date(now);monday.setDate(now.getDate()-((today+6)%7));const dateFor=(day:number)=>{const offset=day===0?6:day-1;const date=new Date(monday);date.setDate(monday.getDate()+offset);return date.getDate()};const selected=schedule.find(x=>x.day===selectedDay);return <ScreenContainer className="px-5 pt-3"><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><View><Text style={styles.kicker}>ORGANIZE SEU RITMO</Text><Text style={styles.title}>Agenda</Text></View><IconButton name="calendar-today"/></View><Text style={styles.helper}>Toque em qualquer dia para ver o treino planejado.</Text><View style={styles.week}>{[1,2,3,4,5,6,0].map(day=><Pressable key={day} onPress={()=>setSelectedDay(day)} style={[styles.day,day===selectedDay&&styles.active]}><Text style={[styles.dayName,day===selectedDay&&styles.activeText]}>{dayLabel(day).slice(0,3).toUpperCase()}</Text><Text style={[styles.dayN,day===selectedDay&&styles.activeText]}>{dateFor(day)}</Text><View style={[styles.dot,schedule.some(x=>x.day===day)&&styles.dotSet]} /></Pressable>)}</View><SectionTitle eyebrow={`${selectedDay===today?"Hoje · ":"Selecionado · "}${dayLabel(selectedDay)}`} title="Treino do dia"/>{selected?<Card style={styles.card}><View style={styles.cardTop}><View><Text style={styles.cardTitle}>{selected.title}</Text><Text style={styles.cardMeta}>{selected.exerciseIds.length} exercícios adicionados</Text></View><IconButton name="delete-outline" onPress={()=>removeSchedule(selected.day)}/></View><Text style={styles.exerciseNames}>{selected.exerciseIds.map(id=>exercises.find(x=>x.id===id)?.name).filter(Boolean).join(" · ")}</Text>{selectedDay===today&&<PrimaryButton label="Começar treino" icon="play-arrow" onPress={()=>router.push("/workout")}/>}</Card>:<Card style={styles.empty}><MaterialIcons name="event-available" size={28} color={palette.lime}/><Text style={styles.emptyTitle}>Dia livre</Text><Text style={styles.emptyText}>Escolha exercícios na Biblioteca e adicione-os a {dayLabel(selectedDay)}.</Text></Card>}<View style={styles.space}/><PrimaryButton label="Montar pela Biblioteca" icon="menu-book" onPress={()=>router.push("/(tabs)/library")}/></ScrollView></ScreenContainer>}
const styles=StyleSheet.create({content:{paddingBottom:30},header:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginBottom:12},kicker:{color:palette.lime,fontSize:10,fontWeight:"900",letterSpacing:1.3},title:{color:palette.text,fontSize:29,fontWeight:"900",marginTop:5},helper:{color:palette.muted,fontSize:12,marginBottom:20},week:{flexDirection:"row",justifyContent:"space-between",marginBottom:30},day:{width:46,height:74,borderRadius:15,backgroundColor:palette.surface,borderWidth:1,borderColor:palette.border,alignItems:"center",justifyContent:"center",gap:3},active:{backgroundColor:palette.lime,borderColor:palette.lime},dayName:{color:palette.muted,fontSize:9,fontWeight:"900"},dayN:{color:palette.text,fontSize:17,fontWeight:"900"},activeText:{color:palette.bg},dot:{width:5,height:5,borderRadius:3,backgroundColor:palette.border},dotSet:{backgroundColor:palette.lime},card:{padding:15},cardTop:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"},cardTitle:{color:palette.text,fontSize:16,fontWeight:"900"},cardMeta:{color:palette.muted,fontSize:11,marginTop:4},exerciseNames:{color:palette.lime,fontSize:12,lineHeight:20,marginTop:15,marginBottom:16},empty:{alignItems:"center",padding:28},emptyTitle:{color:palette.text,fontSize:17,fontWeight:"900",marginTop:10},emptyText:{color:palette.muted,fontSize:12,textAlign:"center",lineHeight:18,marginTop:5},space:{height:28}});
