import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { MaterialIcons } from "@expo/vector-icons";
import { ScreenContainer } from "@/components/screen-container";
import { Card, palette } from "@/components/trennix-ui";
import { askTrennixAI } from "@/lib/trennix/ai";
import { useTrennixStore } from "@/lib/trennix/store";
export default function CoachScreen(){const {profile,schedule}=useTrennixStore();const [text,setText]=useState("");const [loading,setLoading]=useState(false);const [messages,setMessages]=useState<{from:"coach"|"me";body:string}[]>([{from:"coach",body:"Olá. Sou o treinador do TRENNIX. Monte sua agenda e me pergunte sobre seus exercícios."}]);const send=async()=>{if(!text.trim()||loading)return;const question=text.trim();setText("");setMessages(m=>[...m,{from:"me",body:question}]);setLoading(true);try{const answer=await askTrennixAI(question,`Nome: ${profile.name||"não informado"}; idade: ${profile.age||"não informada"}; treinos na agenda: ${schedule.length}`);setMessages(m=>[...m,{from:"coach",body:answer}])}catch(error){setMessages(m=>[...m,{from:"coach",body:error instanceof Error?error.message:"Não consegui responder agora."}])}finally{setLoading(false)}};return <ScreenContainer className="px-5 pt-3"><View style={styles.header}><View><Text style={styles.kicker}>TREINADOR INTELIGENTE</Text><Text style={styles.title}>Chat IA</Text></View><View style={styles.bot}><MaterialIcons name="smart-toy" size={25} color={palette.lime}/></View></View><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>{messages.map((m,i)=><View key={i} style={[styles.bubble,m.from==="me"?styles.mine:styles.theirs]}><Text style={[styles.bubbleText,m.from==="me"&&styles.mineText]}>{m.body}</Text><Text style={[styles.time,m.from==="me"&&styles.mineText]}>{loading&&i===messages.length-1?"...":"agora"}</Text></View>)}{loading&&<Text style={styles.loading}>O treinador está pensando...</Text>}<Card style={styles.tip}><MaterialIcons name="info-outline" size={18} color={palette.lime}/><Text style={styles.tipText}>As respostas dependem da chave configurada e não substituem orientação profissional.</Text></Card></ScrollView><View style={styles.composer}><TextInput value={text} onChangeText={setText} onSubmitEditing={send} returnKeyType="send" placeholder="Pergunte ao treinador..." placeholderTextColor={palette.muted} style={styles.input}/><Pressable onPress={send} style={({pressed})=>[styles.send,pressed&&{opacity:.7}]}><MaterialIcons name="arrow-upward" color={palette.bg} size={20}/></Pressable></View></ScreenContainer>}
const styles=StyleSheet.create({content:{paddingBottom:20},header:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginBottom:22},kicker:{color:palette.lime,fontSize:10,fontWeight:"900",letterSpacing:1.1},title:{color:palette.text,fontSize:29,fontWeight:"900",marginTop:5},bot:{width:52,height:52,borderRadius:26,borderWidth:1,borderColor:palette.green,alignItems:"center",justifyContent:"center",backgroundColor:"#17251a"},bubble:{maxWidth:"86%",padding:14,borderRadius:18,marginBottom:10},theirs:{alignSelf:"flex-start",backgroundColor:palette.surface,borderTopLeftRadius:5},mine:{alignSelf:"flex-end",backgroundColor:palette.lime,borderTopRightRadius:5},bubbleText:{color:palette.text,fontSize:14,lineHeight:20},mineText:{color:palette.bg},time:{color:palette.muted,fontSize:9,textAlign:"right",marginTop:6},loading:{color:palette.muted,fontSize:12,marginBottom:10},tip:{flexDirection:"row",gap:8,alignItems:"center",marginTop:8},tipText:{color:palette.muted,fontSize:11,lineHeight:16,flex:1},composer:{flexDirection:"row",alignItems:"center",gap:8,paddingVertical:10},input:{flex:1,height:50,backgroundColor:palette.surface,borderWidth:1,borderColor:palette.border,borderRadius:16,paddingHorizontal:15,color:palette.text},send:{width:48,height:48,borderRadius:16,backgroundColor:palette.lime,alignItems:"center",justifyContent:"center"}});
