import { ScrollView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { MaterialIcons } from "@expo/vector-icons";
import { ScreenContainer } from "@/components/screen-container";
import { Card, IconButton, palette, SectionTitle } from "@/components/trennix-ui";
import { history } from "@/lib/trennix/data";

export default function HistoryScreen() {
  return <ScreenContainer className="px-5 pt-3"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}><View style={styles.header}><View><Text style={styles.kicker}>SEU CAMINHO</Text><Text style={styles.title}>Histórico</Text></View><IconButton name="insights" /></View><Card style={styles.summary}><View><Text style={styles.summaryLabel}>VOLUME TOTAL · MAIO</Text><Text style={styles.summaryValue}>14.160 <Text style={styles.summaryUnit}>kg</Text></Text><Text style={styles.summarySub}>+12% contra abril</Text></View><View style={styles.chart}>{[35,55,44,78,58,87,65].map((height, i) => <View key={i} style={[styles.bar, { height, backgroundColor: i === 5 ? palette.lime : "#345438" }]} />)}</View></Card><View style={styles.section}><SectionTitle title="Sessões recentes" />{history.map((item) => <Card key={item.id} style={styles.row}><View style={styles.icon}><MaterialIcons name="fitness-center" size={20} color={palette.lime}/></View><View style={styles.copy}><Text style={styles.rowTitle}>{item.title}</Text><Text style={styles.rowMeta}>{item.date} · {item.exercises}</Text></View><View style={styles.volume}><Text style={styles.volumeValue}>{item.volume}</Text><MaterialIcons name="chevron-right" size={18} color={palette.muted}/></View></Card>)}</View></ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { paddingBottom: 28 }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 25 }, kicker: { color: palette.lime, fontSize: 10, fontWeight: "900", letterSpacing: 1.4 }, title: { color: palette.text, fontSize: 29, fontWeight: "900", marginTop: 5 }, summary: { flexDirection: "row", justifyContent: "space-between", minHeight: 155 }, summaryLabel: { color: palette.muted, fontSize: 10, fontWeight: "900", letterSpacing: 1 }, summaryValue: { color: palette.text, fontSize: 29, fontWeight: "900", marginTop: 11 }, summaryUnit: { color: palette.muted, fontSize: 13 }, summarySub: { color: palette.lime, fontSize: 12, marginTop: 6, fontWeight: "700" }, chart: { flexDirection: "row", alignItems: "flex-end", gap: 7, height: 95, paddingTop: 12 }, bar: { width: 10, borderRadius: 5 }, section: { marginTop: 28 }, row: { flexDirection: "row", alignItems: "center", padding: 13, marginBottom: 9 }, icon: { width: 42, height: 42, borderRadius: 13, backgroundColor: "#243522", alignItems: "center", justifyContent: "center" }, copy: { flex: 1, marginLeft: 12 }, rowTitle: { color: palette.text, fontSize: 14, fontWeight: "800" }, rowMeta: { color: palette.muted, fontSize: 11, marginTop: 4 }, volume: { alignItems: "flex-end", gap: 2 }, volumeValue: { color: palette.text, fontSize: 12, fontWeight: "800" }, });
