import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { MaterialIcons } from "@expo/vector-icons";
import { ScreenContainer } from "@/components/screen-container";
import { Card, IconButton, palette, PrimaryButton, SectionTitle } from "@/components/trennix-ui";
import { exercises } from "@/lib/trennix/data";
import { dayLabel, useTrennixStore } from "@/lib/trennix/store";
export default function HomeScreen(){const {profile,schedule}=useTrennixStore();const today=new Date().getDay();const todays=schedule.find(x=>x.day===today);const name=profile.name||"atleta";return <ScreenContainer className="px-5 pt-3"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}><View style={styles.top}><View><Text style={styles.greeting}>Olá, {name}</Text><Text style={styles.sub}>Monte sua evolução no seu ritmo.</Text></View><IconButton name="notifications-none"/></View><SectionTitle eyebrow={`${dayLabel(today)} · ${new Date().getDate()}`} title="Treino de hoje"/>{todays?<Card style={styles.hero}><View style={styles.badge}><Text style={styles.badgeText}>PLANEJADO</Text></View><Text style={styles.heroTitle}>{todays.title}</Text><Text style={styles.heroSub}>{todays.exerciseIds.length} exercícios adicionados</Text><PrimaryButton label="Começar treino" icon="play-arrow" onPress={()=>router.push("/workout")}/></Card>:<Card style={styles.empty}><View style={styles.emptyIcon}><MaterialIcons name="add" color={palette.lime} size={28}/></View><Text style={styles.emptyTitle}>Seu treino começa aqui</Text><Text style={styles.emptyText}>Abra a Biblioteca, escolha um grupo muscular e coloque exercícios no dia que quiser.</Text><PrimaryButton label="Montar treino" icon="menu-book" onPress={()=>router.push("/(tabs)/library")}/></Card>}<View style={styles.space}/><SectionTitle title="Resumo da semana"/><Card style={styles.progress}><View><Text style={styles.label}>TREINOS NA AGENDA</Text><Text style={styles.number}>{schedule.length}<Text style={styles.muted}> / 7</Text></Text><Text style={styles.caption}>{schedule.length?"Dias organizados por você":"Nenhum dia configurado"}</Text></View><View style={styles.ring}><Text style={styles.ringText}>{Math.round(schedule.length/7*100)}%</Text></View></Card><View style={styles.space}/><View style={styles.sectionRow}><SectionTitle title="Próximos dias"/><Pressable onPress={()=>router.push("/(tabs)/agenda")}><Text style={styles.link}>Ver agenda</Text></Pressable></View><Card style={styles.next}>{schedule.filter(x=>x.day!==today).slice(0,3).map(item=><View key={item.day} style={styles.nextRow}><View><Text style={styles.day}>{dayLabel(item.day).toUpperCase()}</Text><Text style={styles.nextTitle}>{item.title}</Text><Text style={styles.nextMeta}>{item.exerciseIds.map(id=>exercises.find(e=>e.id===id)?.name).filter(Boolean).join(" · ")}</Text></View><MaterialIcons name="chevron-right" color={palette.muted} size={20}/></View>)}</Card></ScrollView></ScreenContainer>}
const styles=StyleSheet.create({content:{paddingBottom:30},top:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginBottom:28},greeting:{color:palette.text,fontSize:23,fontWeight:"900"},sub:{color:palette.muted,fontSize:13,marginTop:5},hero:{padding:18},badge:{alignSelf:"flex-start",backgroundColor:palette.lime,borderRadius:7,paddingHorizontal:8,paddingVertical:5,marginBottom:13},badgeText:{color:palette.bg,fontSize:10,fontWeight:"900"},heroTitle:{color:palette.text,fontSize:27,fontWeight:"900"},heroSub:{color:palette.muted,fontSize:13,marginVertical:16},empty:{alignItems:"center",padding:28},emptyIcon:{width:60,height:60,borderRadius:30,backgroundColor:"#243522",alignItems:"center",justifyContent:"center",marginBottom:16},emptyTitle:{color:palette.text,fontSize:19,fontWeight:"900"},emptyText:{color:palette.muted,textAlign:"center",fontSize:13,lineHeight:19,marginTop:8,marginBottom:19},space:{height:27},sectionRow:{flexDirection:"row",alignItems:"center",justifyContent:"space-between"},link:{color:palette.lime,fontSize:12,fontWeight:"800"},progress:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"},label:{color:palette.muted,fontSize:10,fontWeight:"900",letterSpacing:1},number:{color:palette.text,fontSize:32,fontWeight:"900",marginTop:6},muted:{color:palette.muted,fontSize:18},caption:{color:palette.muted,fontSize:11,marginTop:4},ring:{width:67,height:67,borderRadius:34,borderWidth:7,borderColor:palette.elevated,alignItems:"center",justifyContent:"center"},ringText:{color:palette.muted,fontWeight:"900"},next:{paddingVertical:4},nextRow:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",paddingVertical:13,borderBottomWidth:1,borderBottomColor:palette.border},day:{color:palette.lime,fontSize:10,fontWeight:"900",letterSpacing:1},nextTitle:{color:palette.text,fontSize:14,fontWeight:"800",marginTop:4},nextMeta:{color:palette.muted,fontSize:10,marginTop:3}});
